version: 2

jobs:
  build:
    docker:
      - image: carapaceio/htmlvalidator:latest

    steps:
      - checkout

      - run:
          name: validate html
          command: |
            amphtml-validator public/*.html

  deploy-staging:
    docker:
    - image: carapaceio/htmlvalidator:latest

    steps:
    - checkout

    - run:
        name: deploy to staging
        command: |
          firebase use staging
          firebase deploy

  deploy-prod:
    docker:
    - image: carapaceio/htmlvalidator:latest

    steps:
    - checkout

    - run:
        name: deploy to production
        command: |
          firebase use production
          firebase deploy

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
      - deploy-prod:
          requires:
            - build
            - hold
          filters:
            branches:
              only: master